//Image request actions
export const IMAGE_FETCH_REQUESTED = 'IMAGE_FETCH_REQUESTED';
export const IMAGE_FETCH_SUCCESS = 'IMAGE_FETCH_SUCCESS';
export const IMAGE_FETCH_FAILURE = 'IMAGE_FETCH_FAILURE';

export const CHANGE_LIMIT = 'CHANGE_LIMIT';
export const CHANGE_PAGE = 'CHANGE_PAGE';

export const UPDATE_FAVORITES = 'UPDATE_FAVORITES';
